### ISSUE TITLE
duplicated and incomplete `methodsNames`

### ISSUE THREAD

**Issue by WebReflection** [elado/class-private-method-decorator#1]
These three lines are weird:
https://github.com/elado/class-private-method-decorator/blob/master/src/index.js#L4-L6

``` js
const proto = target.prototype
const methodNames = Object.getOwnPropertyNames(proto)
for (let k in proto) methodNames.push(k)
```

If you want both enumerable (for/in) and non enumerable, you just need to use `Object.getOwnPropertyNames` since it returns both.

If you are doing the `for/in` after to include inherited names, then since you know you need to grab them via `Object.getOwnPropertyNames` 'cause by default, classes, have non enumerable properties, you should probably crawl the `proto` via `Object.getPrototypeOf(proto)` until you reach `null` or `Object.prototype` and add all own keys in your way up to the list so that the `Set` will work better and your prototypes won't have surprises.

If it's about something else please let me know.

P.S. you can write `function Class() {}` without problems, I'm sure nobody and nothing will complain ;-)

**Comment by elado** [comment]
@WebReflection thanks! I've revamped the entire code in 2.1.0. Better support for inheritance, static methods, and later prototype changes.

Closing this, feel free to report any other issues.
